### ISSUE TITLE
Error:  Package is invalid. Details: 'Could not load extension icon 'data/icons/120.png'.'.

### ISSUE THREAD

**Issue by vbap** [cluclead/skype-web#1]
Tried to install to Chrome v53.0.2785.89

Received error
Package is invalid. Details: 'Could not load extension icon 'data/icons/120.png'.'.

**Comment by cluclead** [comment]
Thanks for the report. I pushed an update and this issue should have been fixed by now. Let me know if you got this after the upgrade.

**Comment by vbap** [comment]
it's fixed now - thanks!
