### ISSUE TITLE
sign out itself 

### ISSUE THREAD

**Issue by mohanen** [cluclead/skype-web#2]
its signing out automatically. and i am not able to use auto fill. every time  i have to type all or open a new tab and sign in . fire fox

**Comment by cluclead** [comment]
Are you sure your Firefox prefs are not being modified to not remember cookies? You can confirm this by creating a new profile and installing the extension there to give it a try; http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html
